<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-android</TargetFramework>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<ApplicationId>com.wwork.fiwe</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<RuntimeIdentifiers>android-arm64;android-arm;android-x64;android-x86</RuntimeIdentifiers>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<RuntimeIdentifiers>android-arm64;android-arm</RuntimeIdentifiers>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <AndroidKeyStore>False</AndroidKeyStore>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.1.0" />
		<PackageReference Include="Avalonia.Android" Version="11.1.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\FiweClient\FiweClient.App.csproj" />
	</ItemGroup>
</Project>